### ISSUE TITLE
Comments or notes in bags (feature request)

### ISSUE THREAD

**Issue by 9a3eedi** [ros/ros_comm#1157] opened 2017-09-04 07:03 UTC
While working on a project I found that I tended to make a lot of rosbags, but it's very hard to keep track of which bag is what, or what the contents are. For now I set the filename prefix before I record to keep track of things, but sometimes you want to add notes _after_ you record.

It would be very nice if there was a feature to put notes in a bag. One idea is to have rosbag record prompt the user for notes after a record is done.

**Comment by dirk-thomas** [comment] 2017-09-05 22:44
Duplicate of #83. Please see the comment on that issue about an existing external tool which might do what you are looking for.

**Closed as completed by dirk-thomas** 2017-09-05 22:44 UTC
Labels: duplicate
