### ISSUE TITLE
rosbag record size maximum 2GB

### ISSUE THREAD

**Issue by trthanhquang** [ros/ros_comm#534] opened 2014-12-01 22:20 UTC
uint32 max_size = 1048576*C 
Since uint32 max is 4294967295, the max C is only 4095 which is 2GB!!!

**Comment by dirk-thomas** [comment] 2014-12-01 22:30
I assume this is a duplicate of #464. If not please comment.

Please consider to provide a pull request (together with some unit test).

**Closed as completed by dirk-thomas** 2014-12-01 22:30 UTC
Labels: duplicate
