### ISSUE TITLE
roslaunch should have a --no-check-log-dir option

### ISSUE THREAD

**Issue by 130s** [ros/ros_comm#67] opened 2013-01-08 22:38 UTC
Migrated from https://code.ros.org/trac/ros/ticket/3432
Reported by:    watts   Owned by:   kwc
Priority:   major
Attachment available: No
Last modified ago: Mar 2011

---

This option could speed up launches for users who just don't care how big their log directories are.

**Comment by dirk-thomas** [comment] 2013-03-01 00:54
Duplicate of #133

**Closed as completed by dirk-thomas** 2013-03-01 00:54 UTC
Labels: enhancement
