### ISSUE TITLE
rosbag doesn't honor --duration

### ISSUE THREAD

**Issue by ahendrix** [ros/ros_comm#25] opened 2012-11-16 03:34 UTC
Observed behavior:
rosbag with --duration runs forever, and records a bag file for the entire run-time.

$ time rosbag record --duration 5 chatter
[ INFO] [1353036305.828513349]: Subscribing to chatter
[ INFO] [1353036305.831663013]: Recording to 2012-11-15-19-25-05.bag.
^C
real    0m22.536s
user    0m0.264s
sys 0m0.896s
$ rosbag info 2012-11-15-19-25-05.bag 
path:        2012-11-15-19-25-05.bag
version:     2.0
duration:    21.6s
start:       Nov 15 2012 19:25:06.07 (1353036306.07)
end:         Nov 15 2012 19:25:27.67 (1353036327.67)
size:        23.1 KB
messages:    217
compression: none [1/1 chunks]
types:       std_msgs/String [992ce8a1687cec8c8bd883ec73ca41d1]
topics:      chatter   217 msgs    : std_msgs/String

Expected behavior:
rosbag runs for roughly the specified time and then terminates.

**Comment by dirk-thomas** [comment] 2012-11-21 13:47
The duration seems to work fine for me (with the current Groovy packages). I tried the following:
`rostopic pub -r 10 /foo std_msgs/Int32 42`
`rosbag record --duration=1 /foo`
The recording ends automatically after a bit more than one second. I also tried with 3 and 5 seconds which took that much longer and also produced bigger bag files.
Please try to reproduce the problem on your machine with this command sequence.

**Comment by ahendrix** [comment] 2012-11-26 21:45
Confirmed; this is fixed in Groovy.

I can also confirm that this is broken in Fuerte.

**Comment by dirk-thomas** [comment] 2012-11-26 23:14
Let's keep the ticket open until we have checked which change fixed it for Groovy and if that change is a candidate for a backport.

**Comment by dirk-thomas** [comment] 2014-05-01 22:49
Since the issue was resolved and the previous versions are not supported anymore I will close this ticket finally.

**Closed as completed by dirk-thomas** 2014-05-01 22:49 UTC
