### ISSUE TITLE
rosmaster crashed/frozen

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#512] opened 2014-10-14 18:39 UTC
Lots of errors like this in master.log:

```
[rosmaster.threadpool][ERROR] 2014-10-14 11:23:25,358: Traceback (most recent call last):
  File "/home/hendrix/hydro/junior/underlay/src/ros_comm/tools/rosmaster/src/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/home/hendrix/hydro/junior/underlay/src/ros_comm/tools/rosmaster/src/rosmaster/master_api.py", line 189, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```

Full log: https://gist.github.com/anonymous/c7b1430b28ab867c4118

**Comment by dirk-thomas** [comment] 2014-10-14 23:16
Can you please provide further information, e.g. what you ran / how to reproduce the issue?

**Comment by wjwwood** [comment] 2014-10-14 23:29
The error `gaierror: [Errno -2] Name or service not known` is not in the snippet which is visible from the gist, the blob is too big to view raw...

Most of the errors which are visible are:

```
[rosmaster.threadpool][ERROR] 2014-10-13 09:58:43,745: Traceback (most recent call last):
  File "/home/hendrix/hydro/junior/underlay/src/ros_comm/tools/rosmaster/src/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/home/hendrix/hydro/junior/underlay/src/ros_comm/tools/rosmaster/src/rosmaster/master_api.py", line 189, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
```

It looks like a networking issue to me, but like @dirk-thomas said it's hard to tell what the issue is without some context.

**Comment by trainman419** [comment] 2014-10-14 23:43
The symptoms were that the ROS master was still running, but wasn't responding to XMLRPC calls.

I left it running for about a day before it crashed, running various tests on my laptop. I suspect the network config changed or the cable got unplugged overnight; not sure if that's part of the cause or not. The log is the only thing I was able to recover, and it didn't reproduce when I restarted my ROS master.

I'll add more information if I see this again or if I come up with a better way to reproduce it.

**Comment by dirk-thomas** [comment] 2014-10-22 01:12
Until further information to better reproduce it are available I will mark this with the milestone `untargeted`.

**Comment by trainman419** [comment] 2014-10-22 22:56
Saw this again today after starting and stopping a very large number of nodes (50+) a very large number of times (20-100)

**Comment by dirk-thomas** [comment] 2014-12-10 00:58
I will close this since without further information we can't act on it. Please feel free to comment with more information and the ticket can be reopened.

**Closed as completed by dirk-thomas** 2014-12-10 00:58 UTC
