### ISSUE TITLE
rospy: rosparam exceptions when calling from secondary threads  (ros ticket #4029)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#113] opened 2013-01-09 01:08 UTC
I'm seeing exceptions when calling rospy.get_param from secondary threads in my program.

It seems that the method is not thread safe.

I've attached a small unit test which exhibits the behaviour I'm talking about.

trac data:
- Owner: **dthomas**
- Reporter: **jonmace**
- Reported at: **Thu Aug 16 15:13:15 2012**
- URL: https://code.ros.org/trac/ros/ticket/4029

**Comment by tfoote** [comment] 2013-01-09 01:08
[jonmace] Stack trace:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "rosapi_param_threadsafety_bug.py", line 14, in run
    rospy.get_param("example", "blah")
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/client.py", line 403, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/msproxy.py", line 115, in __getitem**
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 856, in putrequest
    raise CannotSendRequest()
CannotSendRequest

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "rosapi_param_threadsafety_bug.py", line 14, in run
    rospy.get_param("example", "blah")
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/client.py", line 403, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/msproxy.py", line 115, in __getitem**
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1294, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1018, in getresponse
    raise ResponseNotReady()
ResponseNotReady

**Comment by mgrrx** [comment] 2018-10-20 20:49
I'd say we can close this issue. It's a duplicate of https://github.com/ros/ros_comm/issues/459

**Comment by dirk-thomas** [comment] 2018-10-29 16:23
Closing - assuming this has been addressed by #461.

**Closed as completed by dirk-thomas** 2018-10-29 16:23 UTC
Labels: bug
