### ISSUE TITLE
Impossible to import * from rospy

### ISSUE THREAD

**Issue by UnexpectedLobster** [ros/ros_comm#2005] opened 2020-07-23 14:35 UTC
Hi, 

Doing 
```python
from rospy import *
```
raises the following exception : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rospy' has no attribute 'NodeProxy'
```
After some investigations, `NodeProxy` doesn't seem to exist anymore in the codebase. Simply removing it from the exports should do the trick.

**Comment by dirk-thomas** [comment] 2020-07-23 15:12
Duplicate of #2004.

**Closed as completed by dirk-thomas** 2020-07-23 15:12 UTC
Labels: duplicate
