### ISSUE TITLE
Ubuntu central repo for 18.04 still has version 1.14.3 

### ISSUE THREAD

**Issue by arunabhcode** [ros/ros_comm#1911] opened 2020-03-17 07:21 UTC
Hi

The ubuntu central repo still has version 1.14.3 instead of 1.14.4 even though the changelog contains the date 2020-02-20. Just wanted to confirm if that's correct and intended?

**Comment by flixr** [comment] 2020-03-17 07:59
Duplicate of #1906

**Closed as completed** 2020-03-17 08:35 UTC
