### ISSUE TITLE
roscpp Timer autostart option

### ISSUE THREAD

**Issue by AbdElRahmanFarhan** [ros/ros_comm#2117] opened 2021-01-09 14:53 UTC
Hi, I am trying to use ros::Timer. when I use the method createTimer from ros::Nodehandle, there is an option called autostart. What I understand is that the timer will not enter its callback unless we use the method start. However. it seems that this option has no effect. I am using ROS melodic.

**Comment by sloretz** [comment] 2021-01-11 17:43
> However. it seems that this option has no effect. I am using ROS melodic.

Seems to work for me using ROS Melodic. If something still isn't working in your set up, please ask a question on https://answers.ros.org per the [ROS Support Guidelines](http://wiki.ros.org/Support). If you do find there's a bug then please post a minimal reproducible example. I'll close this for now since the `autostart` option appears to be working as intended.


```c++
#include <iostream>
#include <ros/ros.h>

void callback(const ros::TimerEvent& event)
{
        std::cout << "Hello from timer callback\n";
}

void callback_autostart_false(const ros::TimerEvent& event)
{
        std::cout << "Hello from timer callback with autostart false\n";
}


int main(int argc, char ** argv)
{
        std::cout << "Hello world\n";
        ros::init(argc, argv, "foobar");
        ros::NodeHandle nh;

        const bool oneshot = false;

        bool autostart = true;
        ros::Timer timer = nh.createTimer(ros::Duration(0.1), callback, oneshot, autostart);

        autostart = false;
        ros::Timer timer_autostart_false = nh.createTimer(ros::Duration(0.1), callback_autostart_false, oneshot, autostart);
        // timer_autostart_false.start();

        ros::spin();
        return 0;
}
```

```
g++ -std=c++14 timer_test.cpp -I/opt/ros/melodic/include /opt/ros/melodic/lib/libroscpp.so /opt/ros/melodic/lib/librostime.so
```

With `start()` commented out

```console
$ ./a.out 
Hello world
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
Hello from timer callback
```

With `start` not commented out

```console
$ ./a.out 
Hello world
Hello from timer callback
Hello from timer callback with autostart false
Hello from timer callback
Hello from timer callback with autostart false
Hello from timer callback
Hello from timer callback with autostart false
Hello from timer callback
```

**Closed as completed by sloretz** 2021-01-11 17:43 UTC
