### ISSUE TITLE
roscpp: message constructors with values for fields  (ros ticket #2723)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#148] opened 2013-01-31 19:13 UTC
Have you guys considered constructors for ros messages that take values for the fields?  It would be nice to be able to say  

```
const Point p(1, 2, 3);
```

instead of 

```
Point p;
p.x = 1;
p.y = 2;
p.z = 3;
```

trac data:
- Owner: **straszheim**
- Reporter: **bhaskara**
- Reported at: **Mon May 17 13:01:10 2010**
- URL: https://code.ros.org/trac/ros/ticket/2723

**Comment by tfoote** [comment] 2013-01-31 19:13
[jfaust] Yes, and it would be very useful for the simple cases, but quickly becomes useless for larger objects.  Python can do this better because of its named argument support.

Since it's easy enough to create a function to do this separately, I don't think this is going to happen any time soon.

**Comment by tfoote** [comment] 2013-01-31 19:13
[baxelrod] I would like this feature as well and thought it would not be too hard to add, so I did.  See the attached files.  

A new constructor is generated with one parameter per message field.  Just like in bhaskara's post above.  If the message field is another message type, it is not treated any differently.  For example:

```
geometry_msgs::Point point(1, 2, 3);
geometry_msgs::Pose pose(point, geometry_msgs::Quaternion(4,5,6,7));
```

The test code tries to exercise the new constructor.  It tests for:
- no parameters (original case)
- a message with all float parameters
- a message that takes other messages as fields
- a message that takes a header
  - int
  - time
  - string
- a message that takes an array

I left the ticket as new because this code still needs to be put into the main ROS tree.  FYI, I modified `msg_gen.py` from the Ubuntu 9.04 "latest" release.

I hope this patch can make it into the next release.

**Comment by tfoote** [comment] 2013-01-31 19:13
[baxelrod] FYI, I updated my attached files to work with the Ubuntu 10.04 "unstable" release on 2011.05.25 to target the upcoming Electric Emys release.

**Comment by tfoote** [comment] 2013-01-31 19:13
[baxelrod] See also: #3469

**Comment by tfoote** [comment] 2013-01-31 19:13
[dthomas] Using positional arguments in C++ constructors for message would lead to unstable code when a message gets updated in the future. Therefore this feature will not be implemented for C++.

In Python this is possible due to the support of keyword arguments. And therefore only Python has that feature.

**Comment by tfoote** [comment] 2013-01-31 19:13
[baxelrod] I don't buy that argument at all.  First of all, there is no requirement that you use keyword arguments in python message constructors.  In-order arguments are perfectly valid.  And second, the fact that C++ is statically typed makes in-order arguments even more stable in C++ than in python.  

So in C++, I think the only thing that can cause instability is if the message author changes the order of the message fields, and the fields happen to have the same type.  

My guess is that in-order and keyword arguments were added to rospy because they are trivial to do in Python, but left out of roscpp because they are more difficult to implement.  Now, the argument for code stability is being used after-the-fact.

So if you are truly concerned with code instability due to possible future message file modifications, then this ticket can stay closed and I will open a new ticket to remove the "*args" parameter in python message constructors.  But in the mean time, I ask that you reconsider adding in this helpful feature that I already implemented.  Not only is this a nice feature to have, it goes a long way to standardizing the rospy/roscpp coding styles.

**Comment by baxelrod-bdai** [comment] 2013-01-31 20:42
@benaxelrod

**Comment by wjwwood** [comment] 2015-06-16 00:51
@benaxelrod FYI, we recently discussed this issue again internally and came to a similar conclusion, but with some leads for potential compromise. @codebot is going to summarize the discussion and post it here.

**Comment by felixvd** [comment] 2017-07-17 08:22
Just for the record, could someone update if this is really not on the roadmap? Not even for basic message types like Point and Pose?

**Comment by dirk-thomas** [comment] 2017-10-04 17:21
@felixvd I am sorry that you didn't get a response on this earlier. @codebot wanted to summarize the result of the discussion.

The problem is that the order of constructor arguments matters in C++. Assuming a message would provide a constructor with `N` arguments now. If the message definition ever gets updated and another field is being added (e.g. in the middle) existing code might silently break since suddenly the positional arguments are mapped to different fields based on their order.

In Python this can easily be avoided by forcing all constructor arguments to be keyword arguments.

For your case of `Point` or `Pose` which are not likely to change in the future that is of course unsatisfying. But currently we don't see a way to specify on a per message level which should / should not have such a constructor. I would recommend that you use a factory function instead, like `create_point_xyz(double x, double y, double z)` which returns a new instance of a point message. Something like this could even be provided in a header from the package containing the message definition.

**Comment by felixvd** [comment] 2017-10-29 05:51
Correct me if I'm wrong, but if the message definition is updated with another field, wouldn't the original constructor just throw an error? The number of arguments or their type would not match. @benaxelrod seemed to say as much.

If I understand right, the only thing that would trip up the constructor is if the order of two fields of the same type changes. I just went through all the major release tags (1.0.0 to 1.12.5) of the common_msgs repo and checked for this. It has never happened even once. However, everyone who has learned ROS had to struggle with these 5-line constructors for the simplest objects.

If you really think generating constructors is too dangerous in general, what about a per-package flag for stable packages? Whoever turns it on for their own package would have to know what they're doing, and everyone who uses common_msgs could write much more readable C++ code.

**Comment by dirk-thomas** [comment] 2017-10-30 18:39
> if the message definition is updated with another field, wouldn't the original constructor just throw an error? The number of arguments or their type would not match.

That is true only in the absence of default values. As soon as default value are possible (as it is the case in ROS 2) that assumption doesn't hold anymore.

> If you really think generating constructors is too dangerous in general, what about a per-package flag for stable packages?

Please see ros/gencpp#32 which proposes a way to specify such custom constructors on a per-message level.

**Comment by dirk-thomas** [comment] 2017-10-30 18:41
I will close this ticket and mark it with "wontfix" since we don't think this can be done generically and the referenced `gencpp` PR proposes a cleaner / safer alternative.

**Closed as completed** 2017-10-30 18:41 UTC
Labels: wontfix

**Comment by ssnover** [comment] 2019-06-02 05:46
I know this is an old thread, and probably the right place to mention it would be wherever the ROS2 discussion about this is/was happening, but I came across this in Googling.

I don't feel that the argument holds water that arguments to a message type could be changed around and that is why everyone who uses ROS and wishes to write readable code should rewrite the same utility functions. A good API is stable, and an author which changes around the order of two parameters with the same type without a really good reason is making a software engineering mistake.

**Comment by JBuschen** [comment] 2019-12-06 09:22
For writing testing, always writing:

`Point p;
p.x = 0;
p.y = 0;
p.z = 1;`

is just hilarious.

**Comment by dirk-thomas** [comment] 2020-02-03 22:27
@ssnover95 @JBuschen you might want to read the above comments again:

> Please see ros/gencpp#32 which proposes a way to specify such custom constructors on a per-message level.

The feature implemented in the referenced PR allows you do exactly that - implement a message specific custom constructor. And if you don't want everyone to write that on their own the obvious path is to propose the enhancement for a specific message to the package which contains that message.

**Comment by caioaamaral** [comment] 2020-02-24 16:23
What if each field was internally an pair of a value and an id name?  
```
std::pair<string name, int8> _field1;
std::pair<string name, int8 value> _field2;
std::pair<string name, uint16 value> _field3;
```
Client would make the desirable pair and pass it to the constructor:

```
std::pair<"field1", 3> my_field1;  // supposed to have a default value
std::pair<"field2", 5> my_field2;
std::pair<"field3", 5> my_field3;
```

and then:

```
SomeRosMessage ros_message(my_field1,  my_field2, my_field3);
SomeRosMessage ros_message(my_field2, my_field3);
```

**Some possible implementation:**
```
class SomeRosMessage{
  public:
  SomeRosMessage(){
    *_field1Ptr = _field1;
    *_field2Ptr = _field2;
    *_field3Ptr = _field3;
    field_map["field1"] = _field1Ptr.get();
    field_map["field2"] = _field2Ptr.get();
    field_map["field3"] = _field3Ptr.get();

  }
  SomeRosMessage(std::pair<string name, int8 value>first_param, std::pair<string name, int8 value> second_param, std::pair<string name, uint16 value> third_param){
    *static_cast<typeid(first_param.second) *>(field_map[first_param.first]) =  first_param.second;  // or some function to dynamically cast void * to some type runtime defined.
    
    (...)
    
    _field1 =  *static_cast<typeid(field_map["field1"])>;
    
    (...)
    
  }

  int8  _field1{0};
  int8 _field2;
  uint16  _field3;

  private:
  std::map<string name, void * valuePtr> field_map;
  std::shared_ptr<int8> _field1Ptr;
  std::shared_ptr<int8> _field2Ptr;
  std::shared_ptr<uint16> _field3Ptr;
```

The core idea is just let Client decide if he wants use message constructors and if he wants, he should implement the "keyword arguments feature" on its side (e.g using std::pair).

**Comment by dirk-thomas** [comment] 2020-02-24 16:48
@caioaamaral Supporting a change like this in ROS is a bit more complicated than the short narrow example above:

* the change must API compatible to be reasonable be deployed (since every code interacts with the generated message API)
* the API of a message must stay compatible when fields are being added in any order
* if the proposed change breaks (which it seems to do) and can only ever be deployed to future ROS distros (since we don't want to break API in an already released distro), and atm ROS Noetic coming out in May is the last planned ROS distro so time for landing such a drastic change is pretty short
* the memory size overhead introduced to each message instance (in your snippet the extra private member variables) seems undesired
