### ISSUE TITLE
rostopic echo of array indices fails

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#480] opened 2014-07-29 17:51 UTC
This is part of the root cause for https://github.com/ros-visualization/rqt_common_plugins/issues/261

When publishing an array message (on topic `/array`):

```
Header header
float32[] values
```

`rostopic echo /array/values[0]` fails, but `rostopic echo /array/values` succeeds. 

This worked on Hydro, and fails on Indigo. It looks like the underlying bug here is a change somewhere in rostopic's `_get_topic_type()`

**Comment by trainman419** [comment] 2014-07-29 18:02
I'm able to reproduce this with the `test_pub.py` node in this package: https://github.com/trainman419/test_publishers

**Comment by dirk-thomas** [comment] 2014-07-29 20:07
Please try #481 and check if it also fixes the problem you have with rqt_plot.

**Comment by trainman419** [comment] 2014-07-29 20:14
I'm not near my Indigo machine at the moment; I'll try to test this when I get home tonight.

**Comment by trainman419** [comment] 2014-07-30 06:30
Confirmed; this fixes rostopic echo for array members, and rqt_plot for the same cases, although I do get some rather ugly stacktraces whlie typing that don't happen in the hydro version: 

```
Traceback (most recent call last):
  File "/home/htpc/catkin_ws/src/rqt_common_plugins/rqt_plot/src/rqt_plot/plot_widget.py", line 208, in on_topic_edit_textChanged
    plottable, message = is_plottable(topic_name)
  File "/home/htpc/catkin_ws/src/rqt_common_plugins/rqt_plot/src/rqt_plot/plot_widget.py", line 108, in is_plottable
    fields, message = get_plot_fields(topic_name)
  File "/home/htpc/catkin_ws/src/rqt_common_plugins/rqt_plot/src/rqt_plot/plot_widget.py", line 49, in get_plot_fields
    topic_type, real_topic, _ = topic_helpers.get_topic_type(topic_name)
  File "<string>", line 421, in get_topic_type
  File "<string>", line 404, in _get_topic_type
  File "<string>", line 305, in msgevalgen
AssertionError: Topic name 'values[0' contains '[' but does not end with ']'
```

**Comment by dirk-thomas** [comment] 2014-07-30 06:35
What exactly did you try when you got the stack trace? From the assertion it looks like you passed a topic name with an open bracket but without a closing one.

**Comment by trainman419** [comment] 2014-07-30 06:37
Yep. I got that stack while typing the full topic name.

**Comment by dirk-thomas** [comment] 2014-07-30 07:03
Can you please post a reproducible example?

**Comment by trainman419** [comment] 2014-07-30 07:11
I used the topic entry box to interactively select the topic in question, using the `test_pub.py` node from my test_publishers package: https://github.com/trainman419/test_publishers

With the test_pub.py node running, run `rqt_plot` (no arguments), and then type the topic name in the Topic box: `/array/values[0]` - upon entering the [ and the 0, you should see errors on the console.

**Comment by dirk-thomas** [comment] 2014-07-30 15:21
So rqt_plot is calling the API with an invalid topic name. Before it was silently ignored - now it prints the assertion. Do you want to modify rqt_plot to not call the API with temporary (invalid) user input? Or should I change the patch to silently ignore invalid input again?

**Comment by trainman419** [comment] 2014-07-30 18:43
rqt_plot is calling get_topic_type to determine what is and is not a valid topic/field name. The previous version of get_topic_type handled this by returning `None` for invalid topics, and rqt_plot then indicated that the topic was invalid.

I don't expect to modify rqt_plot so that it doesn't call get_topic_type with an invalid topic name.

I think it makes sense to wrap the call to get_topic_type in rqt_plot with a try/catch so that this error 
can be passed to the user more gracefully.

**Comment by dirk-thomas** [comment] 2014-08-04 17:02
Sorry, but the last two paragraphs seem to contradict each other:

> I don't expect to modify rqt_plot...
> 
> ...wrap the call to get_topic_type in rqt_plot...

I have modified the pull request to not change API behavior - for an invalid topic it will return `None` as the msg eval function.

**Closed as completed** 2014-08-04 17:36 UTC
Labels: bug
