### ISSUE TITLE
ros_comm having issue in latest release of WSL

### ISSUE THREAD

**Issue by rowanG077** [ros/ros_comm#1186] opened 2017-10-12 13:08 UTC
Hello guys,

I am a user of ros within WSL. I understand there has been some specific work done on this package to ensure the communication works withing WSL. But using the latest build topics are no longer working correctly and I believe a similiar issue was allready encountered here before and fixed. 

I upgrade from Microsoft Windows [Version 10.0.15063] to Microsoft Windows [Version 10.0.16299.15].

I have also create an issue on the wsl page but I have no idea who is at fault her really. So If this is against the rules or something you an delete or close this issue: https://github.com/Microsoft/BashOnWindows/issues/2560

The issue is that if a subscriber is started and listens on a topic without a publisher being there beforehand and then a publisher starts publishing on that topic the nodes remain onconnected. See this roswtf output using the default teleop turtlesim tutorial, by first starting the turtle_sim_node and then running the telop:

```
Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following nodes are unexpectedly connected:
 * unknown (http://DESKTOP-5KR77SI:50230/)->/rosout (/rosout)


Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /teleop_turtle->/turtlesim (/turtle1/cmd_vel)
 * /teleop_turtle->/rosout (/rosout)
 * /turtlesim->/rosout (/rosout)
```

However if you first start the publisher(teleop) and start the subscriber(turtlesim_node) it will work without a problem.

```
Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following nodes are unexpectedly connected:
 * unknown (http://DESKTOP-5KR77SI:50230/)->/rosout (/rosout)


Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /teleop_turtle->/rosout (/rosout)
 * /turtlesim->/rosout (/rosout)
```

I believe the same issue is occuring why rosout is unconnected. 

Here is the output of running roscore which reports no errors.

```
... logging to /root/.ros/log/3533c16a-ae92-11e7-bd23-bc8385db5709/roslaunch-DESKTOP-5KR77SI-12375.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://DESKTOP-5KR77SI:50203/
ros_comm version 1.13.2


SUMMARY
========

PARAMETERS
 * /rosdistro: lunar
 * /rosversion: 1.13.2

NODES

auto-starting new master
process[master]: started with pid [12386]
ROS_MASTER_URI=http://DESKTOP-5KR77SI:11311/

setting /run_id to 3533c16a-ae92-11e7-bd23-bc8385db5709
process[rosout-1]: started with pid [12399]
started core service [/rosout]
```

**Comment by dirk-thomas** [comment] 2017-10-12 15:24
Your description doesn't contain enough information what exact commands you are running. I just assume that running the same on a supported platform like Ubuntu that it will just work since we have plenty of tests which rely on pub / sub communication to be working. Therefore I assume that the problem is specific to WSL. Since you already filled an issue and there are other similar ones pending (e.g. Microsoft/BashOnWindows#1391) I will close this for now.

Please feel free to continue commenting on this ticket. If it turns out that there is something in ROS which needs to change this can be reopened.

**Closed as completed by dirk-thomas** 2017-10-12 15:24 UTC
Labels: duplicate
