### ISSUE TITLE
roscpp fails to build on OS X yosemite

### ISSUE THREAD

**Issue by fferri** [ros/ros_comm#605] opened 2015-04-19 09:37 UTC
Used to build fine -some week ago- on another machine with OS X 10.10.2 (same compiler).
Note that 122 ROS packages before this just build fine.

Configuration:
OS: Mac OS X 10.10.3
Compiler: Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn) x86_64-apple-darwin14.3.0
ROS: Indigo

[roscpp] ==> '/Users/federico/indigo_desktop_ws/build/roscpp/build_env.sh /usr/local/bin/cmake /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp -DCATKIN_DEVEL_PREFIX=/Users/federico/indigo_desktop_ws/devel -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7' in '/Users/federico/indigo_desktop_ws/build/roscpp'
-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /Users/federico/indigo_desktop_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.9")
-- Using PYTHON_EXECUTABLE: /usr/local/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/local/lib/python2.7/site-packages/em.pyc
-- Using empy: /usr/local/lib/python2.7/site-packages/em.pyc
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /Users/federico/indigo_desktop_ws/build/roscpp/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/local/bin/nosetests-2.7
-- catkin 0.6.11
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   signals
--   filesystem
--   system
-- roscpp: 1 messages, 3 services
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Looking for include file ifaddrs.h
-- Looking for include file ifaddrs.h - found
-- Looking for trunc
-- Looking for trunc - found
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:119 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "rosgraph_msgs_gencpp" of target "roscpp" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:119 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "std_msgs_gencpp" of target "roscpp" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   roscpp

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

```
PYTHON_INCLUDE_DIR
PYTHON_LIBRARY
```

-- Build files have been written to: /Users/federico/indigo_desktop_ws/build/roscpp
[roscpp] <== '/Users/federico/indigo_desktop_ws/build/roscpp/build_env.sh /usr/local/bin/cmake /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp -DCATKIN_DEVEL_PREFIX=/Users/federico/indigo_desktop_ws/devel -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_BUILD_TYPE=Release -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7' finished with return code '0'
[roscpp] ==> '/Users/federico/indigo_desktop_ws/build/roscpp/build_env.sh /usr/bin/make -j4 -l4' in '/Users/federico/indigo_desktop_ws/build/roscpp'
Scanning dependencies of target _roscpp_generate_messages_check_deps_Logger
[  0%] Built target _roscpp_generate_messages_check_deps_Logger
Scanning dependencies of target _roscpp_generate_messages_check_deps_SetLoggerLevel
[  0%] Built target _roscpp_generate_messages_check_deps_SetLoggerLevel
Scanning dependencies of target _roscpp_generate_messages_check_deps_Empty
[  0%] Built target _roscpp_generate_messages_check_deps_Empty
Scanning dependencies of target _roscpp_generate_messages_check_deps_GetLoggers
[  0%] Built target _roscpp_generate_messages_check_deps_GetLoggers
Scanning dependencies of target roscpp_generate_messages_cpp
[  1%] Generating C++ code from roscpp/Logger.msg
[  3%] Generating C++ code from roscpp/GetLoggers.srv
[  4%] Generating C++ code from roscpp/SetLoggerLevel.srv
[  6%] Generating C++ code from roscpp/Empty.srv
[  6%] Built target roscpp_generate_messages_cpp
Scanning dependencies of target roscpp_generate_messages_lisp
[  8%] Generating Lisp code from roscpp/Logger.msg
[  9%] Generating Lisp code from roscpp/GetLoggers.srv
[ 11%] Generating Lisp code from roscpp/SetLoggerLevel.srv
[ 13%] Generating Lisp code from roscpp/Empty.srv
[ 13%] Built target roscpp_generate_messages_lisp
Scanning dependencies of target roscpp_gencpp
[ 13%] Built target roscpp_gencpp
Scanning dependencies of target roscpp_generate_messages_py
[ 14%] Generating Python from MSG roscpp/Logger
[ 16%] Generating Python code from SRV roscpp/SetLoggerLevel
[ 18%] Generating Python code from SRV roscpp/Empty
[ 19%] Generating Python code from SRV roscpp/GetLoggers
[ 21%] Generating Python msg __init__.py for roscpp
[ 22%] Generating Python srv **init**.py for roscpp
[ 22%] Built target roscpp_generate_messages_py
Scanning dependencies of target roscpp
[ 24%] Building CXX object CMakeFiles/roscpp.dir/src/libros/master.cpp.o
[ 26%] Building CXX object CMakeFiles/roscpp.dir/src/libros/subscriber.cpp.o
[ 27%] Building CXX object CMakeFiles/roscpp.dir/src/libros/common.cpp.o
[ 29%] Building CXX object CMakeFiles/roscpp.dir/src/libros/publisher_link.cpp.o
[ 31%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_publication.cpp.o
[ 32%] Building CXX object CMakeFiles/roscpp.dir/src/libros/connection.cpp.o
[ 34%] Building CXX object CMakeFiles/roscpp.dir/src/libros/single_subscriber_publisher.cpp.o
[ 36%] Building CXX object CMakeFiles/roscpp.dir/src/libros/param.cpp.o
[ 37%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_server.cpp.o
[ 39%] Building CXX object CMakeFiles/roscpp.dir/src/libros/wall_timer.cpp.o
[ 40%] Building CXX object CMakeFiles/roscpp.dir/src/libros/xmlrpc_manager.cpp.o
[ 42%] Building CXX object CMakeFiles/roscpp.dir/src/libros/publisher.cpp.o
[ 44%] Building CXX object CMakeFiles/roscpp.dir/src/libros/timer.cpp.o
[ 45%] Building CXX object CMakeFiles/roscpp.dir/src/libros/io.cpp.o
[ 47%] Building CXX object CMakeFiles/roscpp.dir/src/libros/names.cpp.o
[ 49%] Building CXX object CMakeFiles/roscpp.dir/src/libros/topic.cpp.o
[ 50%] Building CXX object CMakeFiles/roscpp.dir/src/libros/topic_manager.cpp.o
[ 52%] Building CXX object CMakeFiles/roscpp.dir/src/libros/poll_manager.cpp.o
[ 54%] Building CXX object CMakeFiles/roscpp.dir/src/libros/publication.cpp.o
[ 55%] Building CXX object CMakeFiles/roscpp.dir/src/libros/statistics.cpp.o
[ 57%] Building CXX object CMakeFiles/roscpp.dir/src/libros/intraprocess_subscriber_link.cpp.o
[ 59%] Building CXX object CMakeFiles/roscpp.dir/src/libros/intraprocess_publisher_link.cpp.o
[ 60%] Building CXX object CMakeFiles/roscpp.dir/src/libros/callback_queue.cpp.o
[ 62%] [ 63%] Building CXX object CMakeFiles/roscpp.dir/src/libros/network.cpp.o
Building CXX object CMakeFiles/roscpp.dir/src/libros/service_server_link.cpp.o
[ 65%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_client.cpp.o
[ 67%] Building CXX object CMakeFiles/roscpp.dir/src/libros/node_handle.cpp.o
[ 68%] Building CXX object CMakeFiles/roscpp.dir/src/libros/connection_manager.cpp.o
[ 70%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport/transport.cpp.o
[ 72%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport/transport_udp.cpp.o
[ 73%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport/transport_tcp.cpp.o
[ 75%] Building CXX object CMakeFiles/roscpp.dir/src/libros/subscriber_link.cpp.o
[ 77%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_client_link.cpp.o
[ 78%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport_publisher_link.cpp.o
[ 80%] Building CXX object CMakeFiles/roscpp.dir/src/libros/file_log.cpp.o
[ 81%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport_subscriber_link.cpp.o
[ 83%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_manager.cpp.o
[ 85%] Building CXX object CMakeFiles/roscpp.dir/src/libros/rosout_appender.cpp.o
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp/src/libros/rosout_appender.cpp:35:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp/include/ros/rosout_appender.h:39:
In file included from /Users/federico/indigo_desktop_ws/devel/include/ros/common.h:36:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/rosconsole/include/ros/assert.h:35:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/rosconsole/include/ros/console.h:39:
In file included from /Users/federico/indigo_desktop_ws/src/roscpp_core/rostime/include/ros/time.h:58:
In file included from /usr/local/include/boost/math/special_functions/round.hpp:14:
In file included from /usr/local/include/boost/math/policies/error_handling.hpp:31:
In file included from /usr/local/include/boost/format.hpp:34:
/usr/local/include/boost/format/format_fwd.hpp:24:69: error: no type named 'allocator' in namespace 'std'
        class Tr = BOOST_IO_STD char_traits<Ch>, class Alloc = std::allocator<Ch> >
                                                               ~~~~~^
/usr/local/include/boost/format/format_fwd.hpp:24:78: error: expected ',' or '>' in template-parameter-list
        class Tr = BOOST_IO_STD char_traits<Ch>, class Alloc = std::allocator<Ch> >
                                                                             ^
/usr/local/include/boost/format/format_fwd.hpp:24:83: error: expected unqualified-id
        class Tr = BOOST_IO_STD char_traits<Ch>, class Alloc = std::allocator<Ch> >
                                                                                  ^
/usr/local/include/boost/format/format_fwd.hpp:27:13: error: unknown type name 'basic_format'
    typedef basic_format<char >     format;
            ^
/usr/local/include/boost/format/format_fwd.hpp:27:25: error: expected unqualified-id
    typedef basic_format<char >     format;
                        ^
/usr/local/include/boost/format/format_fwd.hpp:30:13: error: unknown type name 'basic_format'
    typedef basic_format<wchar_t >  wformat;
            ^
/usr/local/include/boost/format/format_fwd.hpp:30:25: error: expected unqualified-id
    typedef basic_format<wchar_t >  wformat;
                        ^
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp/src/libros/rosout_appender.cpp:35:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/roscpp/include/ros/rosout_appender.h:39:
In file included from /Users/federico/indigo_desktop_ws/devel/include/ros/common.h:36:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/rosconsole/include/ros/assert.h:35:
In file included from /Users/federico/indigo_desktop_ws/src/ros_comm/rosconsole/include/ros/console.h:39:
In file included from /Users/federico/indigo_desktop_ws/src/roscpp_core/rostime/include/ros/time.h:58:
In file included from /usr/local/include/boost/math/special_functions/round.hpp:14:
In file included from /usr/local/include/boost/math/policies/error_handling.hpp:31:
In file included from /usr/local/include/boost/format.hpp:35:
/usr/local/include/boost/format/internals_fwd.hpp:32:5: error: unknown type name 'basic_format'
    basic_format<Ch, Tr, Alloc>&
    ^
/usr/local/include/boost/format/internals_fwd.hpp:32:17: error: expected unqualified-id
    basic_format<Ch, Tr, Alloc>&
                ^
/usr/local/include/boost/format/internals_fwd.hpp:37:5: error: unknown type name 'basic_format'
    basic_format<Ch, Tr, Alloc>&
    ^
/usr/local/include/boost/format/internals_fwd.hpp:37:17: error: expected unqualified-id
    basic_format<Ch, Tr, Alloc>&
                ^
/usr/local/include/boost/format/internals_fwd.hpp:48:10: warning: variable templates are a C++14 extension [-Wc++14-extensions]
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
         ^
/usr/local/include/boost/format/internals_fwd.hpp:48:10: error: variable has incomplete type 'void'
/usr/local/include/boost/format/internals_fwd.hpp:48:22: error: use of undeclared identifier 'basic_format'
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                     ^
/usr/local/include/boost/format/internals_fwd.hpp:48:35: error: 'Ch' does not refer to a value
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                                  ^
/usr/local/include/boost/format/internals_fwd.hpp:47:20: note: declared here
    template<class Ch, class Tr, class Alloc, class T>
                   ^
/usr/local/include/boost/format/internals_fwd.hpp:48:38: error: 'Tr' does not refer to a value
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                                     ^
/usr/local/include/boost/format/internals_fwd.hpp:47:30: note: declared here
    template<class Ch, class Tr, class Alloc, class T>
                             ^
/usr/local/include/boost/format/internals_fwd.hpp:48:42: error: 'Alloc' does not refer to a value
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                                         ^
/usr/local/include/boost/format/internals_fwd.hpp:47:40: note: declared here
    template<class Ch, class Tr, class Alloc, class T>
                                       ^
/usr/local/include/boost/format/internals_fwd.hpp:48:50: error: use of undeclared identifier 'self'
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                                                 ^
/usr/local/include/boost/format/internals_fwd.hpp:48:56: error: 'T' does not refer to a value
    void distribute (basic_format<Ch,Tr, Alloc>& self, T x);
                                                       ^
/usr/local/include/boost/format/internals_fwd.hpp:47:53: note: declared here
    template<class Ch, class Tr, class Alloc, class T>
                                                    ^
/usr/local/include/boost/format/internals_fwd.hpp:51:5: error: unknown type name 'basic_format'
    basic_format<Ch, Tr, Alloc>&
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 86%] Building CXX object CMakeFiles/roscpp.dir/src/libros/init.cpp.o
[ 88%] Building CXX object CMakeFiles/roscpp.dir/src/libros/subscription.cpp.o
1 warning and 20 errors generated.
make[2]: **\* [CMakeFiles/roscpp.dir/src/libros/rosout_appender.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [CMakeFiles/roscpp.dir/all] Error 2
make: **\* [all] Error 2
make: INTERNAL: Exiting with 5 jobserver tokens available; should be 4!
[roscpp] <== '/Users/federico/indigo_desktop_ws/build/roscpp/build_env.sh /usr/bin/make -j4 -l4' failed with return code '2'

**Comment by fferri** [comment] 2015-04-19 10:24
I checked on the other machine (OS X 10.10.2), which previously built ROS Indigo fine.
Now it fails with this very same error.

I guess this is related to Xcode 6.3 / Xcode Command Line Tools 6.3. Now both machines have the toolchain provided by Xcode 6.3.

**Comment by fferri** [comment] 2015-04-19 12:58
I confirm that downgrading to Xcode 6.2 and Xcode Command Line Tools 6.2 solves this issue :-)

**Comment by wjwwood** [comment] 2015-04-20 00:45
I'm going to close this as a duplicate of https://github.com/ros/ros_comm/issues/604

**Closed as completed by wjwwood** 2015-04-20 00:45 UTC
