### ISSUE TITLE
waitForMessage compile error with c++11 

### ISSUE THREAD

**Issue by phil0stine** [ros/ros_comm#488] opened 2014-08-12 16:13 UTC
Just installed Indigo on 14.04, ran into this issue with gcc 4.8.2. 

For both rosbuild and catkin, the following will not compile if the c++0x or c++11 flag is set, but will compile if the flag is disabled.

The error:

```
In file included from /opt/ros/indigo/include/ros/ros.h:55:0,
                 from /home/phil/catkin_ws/src/tst_wait/src/tst.cpp:1:
/opt/ros/indigo/include/ros/topic.h: In instantiation of ‘bool ros::topic::SubscribeHelper<M>::hasMessage() [with M = std_msgs::String_<std::allocator<void> >]’:
/opt/ros/indigo/include/ros/topic.h:92:39:   required from ‘boost::shared_ptr<const M> ros::topic::waitForMessage(const string&, ros::NodeHandle&, ros::Duration) [with M = std_msgs::String_<std::allocator<void> >; std::string = std::basic_string<char>]’
/opt/ros/indigo/include/ros/topic.h:108:54:   required from ‘boost::shared_ptr<const M> ros::topic::waitForMessage(const string&) [with M = std_msgs::String_<std::allocator<void> >; std::string = std::basic_string<char>]’
/home/phil/catkin_ws/src/tst_wait/src/tst.cpp:7:89:   required from here
/opt/ros/indigo/include/ros/topic.h:64:12: error: cannot convert ‘ros::topic::SubscribeHelper<std_msgs::String_<std::allocator<void> > >::MConstPtr {aka boost::shared_ptr<const std_msgs::String_<std::allocator<void> > >}’ to ‘bool’ in return
     return message_;
```

The program:

``` C++
#include <ros/ros.h>
#include <std_msgs/String.h>

int main(int argc, char **argv)
{
  ros::init(argc, argv, "listener");
  std_msgs::StringConstPtr msg = ros::topic::waitForMessage<std_msgs::String>("/chatter");
  if (msg) std::cout<<"Msg received!"<<std::endl;
  else std::cout<<"No message!"<<std::endl;
  return 0;
}
```

**Comment by dirk-thomas** [comment] 2014-08-12 16:16
Duplicate of #484

**Closed as completed by dirk-thomas** 2014-08-12 16:16 UTC
Labels: duplicate
