### ISSUE TITLE
Rosbag duration can finish too early

### ISSUE THREAD

**Issue by eirik-strand** [ros/ros_comm#1644] opened 2019-03-04 19:49 UTC
I have not done a lot of tests with this issue, but I think it can be reproduced. I have a lot of topics, and will not record more than 1s of data. If it takes more than 1s to start the subscribers, everything just hangs. I guess that check_duration finishes before all subscribers got something on the topic. 

If you have a a long list of topics, doing:
`rosbag record --all --duration="0.1s" `
Will cause it to just hang and never finish
if not I guess you can try `0.01s `

**Comment by cwecht** [comment] 2019-03-05 15:48
I was able to reproduce this bug. The hangig is caused by a deadlock involving Recorders queue_mutex_ and TopicManagers advertised_topics_mutex_) caused by calling ros::shutdown in Recorder::checkDuration during the queue_mutex_ lock.

**Comment by cwecht** [comment] 2019-03-05 16:50
Ok, I was wrong about that, it is even worse: the deadlock involves TopicManagers::advertised_topics_mutex TopicManagers::subs_mutex_.

**Comment by dirk-thomas** [comment] 2019-03-08 19:28
Addressed by #1645.

**Closed as completed by dirk-thomas** 2019-03-08 19:28 UTC
Labels: bug
