### ISSUE TITLE
Custom Messages fail to import in python, naming issues

### ISSUE THREAD

**Issue by akudoma** [ros/ros_comm#320] opened 2013-11-20 15:04 UTC
I have searched and have not found any other ticket relating to this, so forgive me if this is a duplicate. 

I followed the tutorial for creating custom messages as per the following link: http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv

The build worked and rosmsg show found the custom message and its details correctly. However, upon importing into the python the module is not found: “ImportError: No module named ttm_track” where ttm_track was my custom message which only holds a single string called Test.

Upon further investigation of my python path I found that under:
…/catkin_ws/devel/lib/python2.7/dist-packages

I had a folder called nmea_ttm which is my node's package name, not the message name.

Continuing into the directory structure I find:
./dist-packages/nmea_ttm/msg/
ttm_track.py and associated files.

So instead of importing my message using:

from ttm_track import Test

I use
from nmea_ttm.msg import ttm_track as Test

And everything works as expected.

I am not sure if this is a product of something I have done, but this is a fresh install and I have followed the tutorials closely, leading me to think this might be a bug.

Below are my setup details:
Ubuntu 12.04 32 bit
I followed the instructions for ROS install per http://wiki.ros.org/hydro/Installation/Ubuntu
Using the deb package from http://packages.ros.org/ros/ubuntu precise main
Running the apt-get command sudo apt-get install ros-hydro-desktop-full
The roscore command shows I am running ros_comm version 1.9.50

**Comment by tfoote** [comment] 2013-11-20 16:53
From your description that looks like expected behavior.  Generated python code goes into the .msg submodule inside your package module.  See the example code here with the same sort of import: http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29 

What behavior were you expecting?

**Comment by akudoma** [comment] 2013-11-20 17:09
I was expecting the same behavior as described by the link you shared. In the example, it shows the import as:
from std_msgs.msg import String
what I would expect then to do with my code is
from ttm_track.msg import Test
since my custom message is ttm_track.msg. However no such module exists. Instead my ttm_track.msg is compiled as nmea_ttm.msg
Is this expected behavior?

**Comment by dirk-thomas** [comment] 2013-11-20 17:50
All messages are places into a subfolder _msg_ folder under the folder named after your _package_. That is why you have to write:

```
from nmea_ttm.msg ...
```

An in this folder for each message you created (e.g. ttm_track) one Python file is generated. So you always import your messages in the format:

```
from MY_PACKAGE_NAME.msg import MY_MESSAGE_NAME
```

I am closing this ticket since what you describe is correct behavior as documented in the tutorials.

**Closed as completed by dirk-thomas** 2013-11-20 17:50 UTC
Labels: invalid

**Comment by jbcolme** [comment] 2015-08-04 10:25
That's not in the tutorials. And if it is, is not clear at all. That's way there is confusion about this.

**Comment by tfoote** [comment] 2015-08-04 19:06
This is covered in the [Defining Custom Messages Tutorial](http://wiki.ros.org/ROS/Tutorials/DefiningCustomMessages)

**Comment by jbcolme** [comment] 2015-08-05 07:32
It is not... in that page there is no reference as to how load a python
custom message made with a message file, and the name convention of such
module. The only example is using a standard message, which is hardly a
custom message. I'm not trying to be an arse, I just want to point out that
the documentation could be improved. A tutorial of a custom message that
uses a standard string as a message is hardy a custom message... come on...

2015-08-04 21:06 GMT+02:00 Tully Foote notifications@github.com:

**Comment by wjwwood** [comment] 2015-08-06 01:38
From the tutorial:

> Messages are put into a namespace that matches the name of the package

Probably the disconnect is that `std_msgs/String` is exactly the same thing as having your own custom message, i.e. the "standard messages" are not special. So if you have a custom message it's exactly the same as the standard ones:
- `std_msgs/String` => `#include <std_msgs/String.hpp>` or `from std_msgs.msg import String`
- `my_pkg/MyMsg` => `#include <my_pkg/MyMsg.hpp>` or `from my_pkg.msg import MyMsg`

If you know of a way to improve what's in the the above linked page, please feel free to change it. You can comment here if you've made a change and I'd be happy to review it.

**Comment by pierbiag** [comment] 2018-05-06 18:19
I agree with @jbcolme , from the tutorial this naming convention is not clear at all, while this issue (especially @wjwwood 's last message) made it as clear as it should be in the tutorial.

**Comment by dirk-thomas** [comment] 2018-05-07 15:58
@pierbiag The comment from @wjwwood still applies:

> If you know of a way to improve what's in the the above linked page, please feel free to change it. You can comment here if you've made a change and I'd be happy to review it.
