### ISSUE TITLE
Rosbags consume all memory (and/or leak?)

### ISSUE THREAD

**Issue by harlowja** [ros/ros_comm#1742] opened 2019-07-06 21:37 UTC
So looking at the bag.h it appears that when a bag is opened in write mode only that every single entry that is written gets an index entry written into ``connection_indexes_`` which means that every single message (or nearly every one, depending on timing) will cause ``connection_indexes_`` to get bigger and bigger and bigger (even though it will never be used in write only mode); This eventually (for large bags) grows to a very large ``connection_indexes_`` size (which may or may not take up a large portion of memory for something that is never used in write only mode in the first place, especially say when a bag contains hundreds of thousands or millions of messages...).

Affected lines seem to be:

https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosbag_storage/include/rosbag/bag.h#L585-L586

It's easy to see this problem happen, open a bag (or multiple) and then write to them in a loop (from some other rosbag playing messages); eventually if u have a long enough bag to play you will just continue getting new messages into ``connection_indexes_`` and if the bag is big enough you can outrun available memory...

**Comment by dirk-thomas** [comment] 2019-08-07 23:01
I guess the fact that the index if kept in memory for efficient access is by design. Please consider to contribute if you think this should be improved.

**Comment by harlowja** [comment] 2019-08-07 23:36
Except in write-only mode, there isn't any access (efficient or not) in the first place (and therefore memory shouldn't be wasted/accumulated for something that is not used) :-/

**Comment by Arnatious** [comment] 2019-08-22 21:50
Can confirm that the only usage of `connection_indexes_` is in `Bag::readConnectionIndexRecord200()`.

Should be a simple matter to only append to it when `mode_` is `Read`. I'll get on it.

EDIT: by that I mean not bother tracking it during writes since there is no read/write mode.

**Comment by dirk-thomas** [comment] 2019-10-03 21:49
Assuming #1798 addressed the problem I will close this ticket. Please feel free to continue commenting and if necessary the ticket can be reopened.

**Closed as completed by dirk-thomas** 2019-10-03 21:49 UTC
Labels: enhancement
