### ISSUE TITLE
roslaunch: Allow substitution args in rosparam list

### ISSUE THREAD

**Issue by 130s** [ros/ros_comm#101] opened 2013-01-09 00:37 UTC
Migrated from https://code.ros.org/trac/ros/ticket/4015
Reported by:    weiin   Owned by:   kwc
Priority:   minor 
Last modified ago: Jul 2012

---

I am trying to achieve this:  http://answers.ros.org/question/39085/what-is-the-correct-way-to-set-args-in-rosparam/ As roslaunch parses text inside <rosparam> using yaml parser, substitution args cannot be passed into it when there is a parameter list.

**Comment by malban** [comment] 2013-01-28 16:10
+1  This would make managing launch configurations much easier.

**Comment by dirk-thomas** [comment] 2013-04-01 09:33
Duplicate of #50.
As discussed there this should be achieved differently.

**Closed as completed by dirk-thomas** 2013-04-01 09:33 UTC
Labels: enhancement
