### ISSUE TITLE
gmock support much like gtest

### ISSUE THREAD

**Issue by kunaltyagi** [ros/ros_comm#567] opened 2015-02-11 00:19 UTC
Using a good mocking framework is a headache, and especially since ROS already supports gtest, can't the functionality be extended to google-mock framework on similar lines?

**Comment by dirk-thomas** [comment] 2015-02-11 00:20
Duplicate of ros/catkin#699.

**Closed as completed by dirk-thomas** 2015-02-11 00:20 UTC
Labels: duplicate

**Comment by kunaltyagi** [comment] 2015-02-11 00:22
Sorry, is there a bounty?

**Comment by tfoote** [comment] 2015-02-11 00:26
There's not a bounty. We tried turning on bounty source, but haven't actively been using it and have not turned it off.
